/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AuthorizedLayoutImport } from "./routes/_authorized-layout";
import { Route as AuthLayoutImport } from "./routes/_auth-layout";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthorizedLayoutAccountImport } from "./routes/_authorized-layout/account";
import { Route as AuthorizedLayoutDashboardLayoutImport } from "./routes/_authorized-layout/_dashboard-layout";
import { Route as AuthLayoutSignUpImport } from "./routes/_auth-layout/sign-up";
import { Route as AuthLayoutSignInImport } from "./routes/_auth-layout/sign-in";
import { Route as AuthLayoutAuthVerificationImport } from "./routes/_auth-layout/auth-verification";
import { Route as AuthorizedLayoutStoresIndexImport } from "./routes/_authorized-layout/stores/index";
import { Route as AuthorizedLayoutStoresCreateImport } from "./routes/_authorized-layout/stores/create";
import { Route as AuthorizedLayoutDashboardLayoutOverviewImport } from "./routes/_authorized-layout/_dashboard-layout/overview";
import { Route as AuthorizedLayoutDashboardLayoutInventoryImport } from "./routes/_authorized-layout/_dashboard-layout/inventory";
import { Route as AuthorizedLayoutDashboardLayoutFilesImport } from "./routes/_authorized-layout/_dashboard-layout/files";
import { Route as AuthorizedLayoutDashboardLayoutCustomersImport } from "./routes/_authorized-layout/_dashboard-layout/customers";
import { Route as AuthorizedLayoutDashboardLayoutCollectionsImport } from "./routes/_authorized-layout/_dashboard-layout/collections";
import { Route as AuthorizedLayoutDashboardLayoutCategoriesImport } from "./routes/_authorized-layout/_dashboard-layout/categories";
import { Route as AuthorizedLayoutDashboardLayoutSettingsIndexImport } from "./routes/_authorized-layout/_dashboard-layout/settings/index";
import { Route as AuthorizedLayoutDashboardLayoutProductsIndexImport } from "./routes/_authorized-layout/_dashboard-layout/products/index";
import { Route as AuthorizedLayoutDashboardLayoutOrdersIndexImport } from "./routes/_authorized-layout/_dashboard-layout/orders/index";
import { Route as AuthorizedLayoutDashboardLayoutSettingsGeneralImport } from "./routes/_authorized-layout/_dashboard-layout/settings/general";
import { Route as AuthorizedLayoutDashboardLayoutProductsIdImport } from "./routes/_authorized-layout/_dashboard-layout/products/$id";
import { Route as AuthorizedLayoutDashboardLayoutOrdersCreateImport } from "./routes/_authorized-layout/_dashboard-layout/orders/create";
import { Route as AuthorizedLayoutDashboardLayoutOrdersIdImport } from "./routes/_authorized-layout/_dashboard-layout/orders/$id";

// Create/Update Routes

const AuthorizedLayoutRoute = AuthorizedLayoutImport.update({
  id: "/_authorized-layout",
  getParentRoute: () => rootRoute,
} as any);

const AuthLayoutRoute = AuthLayoutImport.update({
  id: "/_auth-layout",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthorizedLayoutAccountRoute = AuthorizedLayoutAccountImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthorizedLayoutRoute,
} as any);

const AuthorizedLayoutDashboardLayoutRoute =
  AuthorizedLayoutDashboardLayoutImport.update({
    id: "/_dashboard-layout",
    getParentRoute: () => AuthorizedLayoutRoute,
  } as any);

const AuthLayoutSignUpRoute = AuthLayoutSignUpImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthLayoutRoute,
} as any);

const AuthLayoutSignInRoute = AuthLayoutSignInImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthLayoutRoute,
} as any);

const AuthLayoutAuthVerificationRoute = AuthLayoutAuthVerificationImport.update(
  {
    id: "/auth-verification",
    path: "/auth-verification",
    getParentRoute: () => AuthLayoutRoute,
  } as any,
);

const AuthorizedLayoutStoresIndexRoute =
  AuthorizedLayoutStoresIndexImport.update({
    id: "/stores/",
    path: "/stores/",
    getParentRoute: () => AuthorizedLayoutRoute,
  } as any);

const AuthorizedLayoutStoresCreateRoute =
  AuthorizedLayoutStoresCreateImport.update({
    id: "/stores/create",
    path: "/stores/create",
    getParentRoute: () => AuthorizedLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutOverviewRoute =
  AuthorizedLayoutDashboardLayoutOverviewImport.update({
    id: "/overview",
    path: "/overview",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutInventoryRoute =
  AuthorizedLayoutDashboardLayoutInventoryImport.update({
    id: "/inventory",
    path: "/inventory",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutFilesRoute =
  AuthorizedLayoutDashboardLayoutFilesImport.update({
    id: "/files",
    path: "/files",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutCustomersRoute =
  AuthorizedLayoutDashboardLayoutCustomersImport.update({
    id: "/customers",
    path: "/customers",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutCollectionsRoute =
  AuthorizedLayoutDashboardLayoutCollectionsImport.update({
    id: "/collections",
    path: "/collections",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutCategoriesRoute =
  AuthorizedLayoutDashboardLayoutCategoriesImport.update({
    id: "/categories",
    path: "/categories",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutSettingsIndexRoute =
  AuthorizedLayoutDashboardLayoutSettingsIndexImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutProductsIndexRoute =
  AuthorizedLayoutDashboardLayoutProductsIndexImport.update({
    id: "/products/",
    path: "/products/",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutOrdersIndexRoute =
  AuthorizedLayoutDashboardLayoutOrdersIndexImport.update({
    id: "/orders/",
    path: "/orders/",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutSettingsGeneralRoute =
  AuthorizedLayoutDashboardLayoutSettingsGeneralImport.update({
    id: "/settings/general",
    path: "/settings/general",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutProductsIdRoute =
  AuthorizedLayoutDashboardLayoutProductsIdImport.update({
    id: "/products/$id",
    path: "/products/$id",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutOrdersCreateRoute =
  AuthorizedLayoutDashboardLayoutOrdersCreateImport.update({
    id: "/orders/create",
    path: "/orders/create",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

const AuthorizedLayoutDashboardLayoutOrdersIdRoute =
  AuthorizedLayoutDashboardLayoutOrdersIdImport.update({
    id: "/orders/$id",
    path: "/orders/$id",
    getParentRoute: () => AuthorizedLayoutDashboardLayoutRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth-layout": {
      id: "/_auth-layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_authorized-layout": {
      id: "/_authorized-layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthorizedLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth-layout/auth-verification": {
      id: "/_auth-layout/auth-verification";
      path: "/auth-verification";
      fullPath: "/auth-verification";
      preLoaderRoute: typeof AuthLayoutAuthVerificationImport;
      parentRoute: typeof AuthLayoutImport;
    };
    "/_auth-layout/sign-in": {
      id: "/_auth-layout/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof AuthLayoutSignInImport;
      parentRoute: typeof AuthLayoutImport;
    };
    "/_auth-layout/sign-up": {
      id: "/_auth-layout/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof AuthLayoutSignUpImport;
      parentRoute: typeof AuthLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout": {
      id: "/_authorized-layout/_dashboard-layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutImport;
      parentRoute: typeof AuthorizedLayoutImport;
    };
    "/_authorized-layout/account": {
      id: "/_authorized-layout/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AuthorizedLayoutAccountImport;
      parentRoute: typeof AuthorizedLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/categories": {
      id: "/_authorized-layout/_dashboard-layout/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutCategoriesImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/collections": {
      id: "/_authorized-layout/_dashboard-layout/collections";
      path: "/collections";
      fullPath: "/collections";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutCollectionsImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/customers": {
      id: "/_authorized-layout/_dashboard-layout/customers";
      path: "/customers";
      fullPath: "/customers";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutCustomersImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/files": {
      id: "/_authorized-layout/_dashboard-layout/files";
      path: "/files";
      fullPath: "/files";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutFilesImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/inventory": {
      id: "/_authorized-layout/_dashboard-layout/inventory";
      path: "/inventory";
      fullPath: "/inventory";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutInventoryImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/overview": {
      id: "/_authorized-layout/_dashboard-layout/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutOverviewImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/stores/create": {
      id: "/_authorized-layout/stores/create";
      path: "/stores/create";
      fullPath: "/stores/create";
      preLoaderRoute: typeof AuthorizedLayoutStoresCreateImport;
      parentRoute: typeof AuthorizedLayoutImport;
    };
    "/_authorized-layout/stores/": {
      id: "/_authorized-layout/stores/";
      path: "/stores";
      fullPath: "/stores";
      preLoaderRoute: typeof AuthorizedLayoutStoresIndexImport;
      parentRoute: typeof AuthorizedLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/orders/$id": {
      id: "/_authorized-layout/_dashboard-layout/orders/$id";
      path: "/orders/$id";
      fullPath: "/orders/$id";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutOrdersIdImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/orders/create": {
      id: "/_authorized-layout/_dashboard-layout/orders/create";
      path: "/orders/create";
      fullPath: "/orders/create";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutOrdersCreateImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/products/$id": {
      id: "/_authorized-layout/_dashboard-layout/products/$id";
      path: "/products/$id";
      fullPath: "/products/$id";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutProductsIdImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/settings/general": {
      id: "/_authorized-layout/_dashboard-layout/settings/general";
      path: "/settings/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutSettingsGeneralImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/orders/": {
      id: "/_authorized-layout/_dashboard-layout/orders/";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutOrdersIndexImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/products/": {
      id: "/_authorized-layout/_dashboard-layout/products/";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutProductsIndexImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
    "/_authorized-layout/_dashboard-layout/settings/": {
      id: "/_authorized-layout/_dashboard-layout/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthorizedLayoutDashboardLayoutSettingsIndexImport;
      parentRoute: typeof AuthorizedLayoutDashboardLayoutImport;
    };
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutAuthVerificationRoute: typeof AuthLayoutAuthVerificationRoute;
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute;
  AuthLayoutSignUpRoute: typeof AuthLayoutSignUpRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthVerificationRoute: AuthLayoutAuthVerificationRoute,
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
  AuthLayoutSignUpRoute: AuthLayoutSignUpRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
);

interface AuthorizedLayoutDashboardLayoutRouteChildren {
  AuthorizedLayoutDashboardLayoutCategoriesRoute: typeof AuthorizedLayoutDashboardLayoutCategoriesRoute;
  AuthorizedLayoutDashboardLayoutCollectionsRoute: typeof AuthorizedLayoutDashboardLayoutCollectionsRoute;
  AuthorizedLayoutDashboardLayoutCustomersRoute: typeof AuthorizedLayoutDashboardLayoutCustomersRoute;
  AuthorizedLayoutDashboardLayoutFilesRoute: typeof AuthorizedLayoutDashboardLayoutFilesRoute;
  AuthorizedLayoutDashboardLayoutInventoryRoute: typeof AuthorizedLayoutDashboardLayoutInventoryRoute;
  AuthorizedLayoutDashboardLayoutOverviewRoute: typeof AuthorizedLayoutDashboardLayoutOverviewRoute;
  AuthorizedLayoutDashboardLayoutOrdersIdRoute: typeof AuthorizedLayoutDashboardLayoutOrdersIdRoute;
  AuthorizedLayoutDashboardLayoutOrdersCreateRoute: typeof AuthorizedLayoutDashboardLayoutOrdersCreateRoute;
  AuthorizedLayoutDashboardLayoutProductsIdRoute: typeof AuthorizedLayoutDashboardLayoutProductsIdRoute;
  AuthorizedLayoutDashboardLayoutSettingsGeneralRoute: typeof AuthorizedLayoutDashboardLayoutSettingsGeneralRoute;
  AuthorizedLayoutDashboardLayoutOrdersIndexRoute: typeof AuthorizedLayoutDashboardLayoutOrdersIndexRoute;
  AuthorizedLayoutDashboardLayoutProductsIndexRoute: typeof AuthorizedLayoutDashboardLayoutProductsIndexRoute;
  AuthorizedLayoutDashboardLayoutSettingsIndexRoute: typeof AuthorizedLayoutDashboardLayoutSettingsIndexRoute;
}

const AuthorizedLayoutDashboardLayoutRouteChildren: AuthorizedLayoutDashboardLayoutRouteChildren =
  {
    AuthorizedLayoutDashboardLayoutCategoriesRoute:
      AuthorizedLayoutDashboardLayoutCategoriesRoute,
    AuthorizedLayoutDashboardLayoutCollectionsRoute:
      AuthorizedLayoutDashboardLayoutCollectionsRoute,
    AuthorizedLayoutDashboardLayoutCustomersRoute:
      AuthorizedLayoutDashboardLayoutCustomersRoute,
    AuthorizedLayoutDashboardLayoutFilesRoute:
      AuthorizedLayoutDashboardLayoutFilesRoute,
    AuthorizedLayoutDashboardLayoutInventoryRoute:
      AuthorizedLayoutDashboardLayoutInventoryRoute,
    AuthorizedLayoutDashboardLayoutOverviewRoute:
      AuthorizedLayoutDashboardLayoutOverviewRoute,
    AuthorizedLayoutDashboardLayoutOrdersIdRoute:
      AuthorizedLayoutDashboardLayoutOrdersIdRoute,
    AuthorizedLayoutDashboardLayoutOrdersCreateRoute:
      AuthorizedLayoutDashboardLayoutOrdersCreateRoute,
    AuthorizedLayoutDashboardLayoutProductsIdRoute:
      AuthorizedLayoutDashboardLayoutProductsIdRoute,
    AuthorizedLayoutDashboardLayoutSettingsGeneralRoute:
      AuthorizedLayoutDashboardLayoutSettingsGeneralRoute,
    AuthorizedLayoutDashboardLayoutOrdersIndexRoute:
      AuthorizedLayoutDashboardLayoutOrdersIndexRoute,
    AuthorizedLayoutDashboardLayoutProductsIndexRoute:
      AuthorizedLayoutDashboardLayoutProductsIndexRoute,
    AuthorizedLayoutDashboardLayoutSettingsIndexRoute:
      AuthorizedLayoutDashboardLayoutSettingsIndexRoute,
  };

const AuthorizedLayoutDashboardLayoutRouteWithChildren =
  AuthorizedLayoutDashboardLayoutRoute._addFileChildren(
    AuthorizedLayoutDashboardLayoutRouteChildren,
  );

interface AuthorizedLayoutRouteChildren {
  AuthorizedLayoutDashboardLayoutRoute: typeof AuthorizedLayoutDashboardLayoutRouteWithChildren;
  AuthorizedLayoutAccountRoute: typeof AuthorizedLayoutAccountRoute;
  AuthorizedLayoutStoresCreateRoute: typeof AuthorizedLayoutStoresCreateRoute;
  AuthorizedLayoutStoresIndexRoute: typeof AuthorizedLayoutStoresIndexRoute;
}

const AuthorizedLayoutRouteChildren: AuthorizedLayoutRouteChildren = {
  AuthorizedLayoutDashboardLayoutRoute:
    AuthorizedLayoutDashboardLayoutRouteWithChildren,
  AuthorizedLayoutAccountRoute: AuthorizedLayoutAccountRoute,
  AuthorizedLayoutStoresCreateRoute: AuthorizedLayoutStoresCreateRoute,
  AuthorizedLayoutStoresIndexRoute: AuthorizedLayoutStoresIndexRoute,
};

const AuthorizedLayoutRouteWithChildren =
  AuthorizedLayoutRoute._addFileChildren(AuthorizedLayoutRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthorizedLayoutDashboardLayoutRouteWithChildren;
  "/auth-verification": typeof AuthLayoutAuthVerificationRoute;
  "/sign-in": typeof AuthLayoutSignInRoute;
  "/sign-up": typeof AuthLayoutSignUpRoute;
  "/account": typeof AuthorizedLayoutAccountRoute;
  "/categories": typeof AuthorizedLayoutDashboardLayoutCategoriesRoute;
  "/collections": typeof AuthorizedLayoutDashboardLayoutCollectionsRoute;
  "/customers": typeof AuthorizedLayoutDashboardLayoutCustomersRoute;
  "/files": typeof AuthorizedLayoutDashboardLayoutFilesRoute;
  "/inventory": typeof AuthorizedLayoutDashboardLayoutInventoryRoute;
  "/overview": typeof AuthorizedLayoutDashboardLayoutOverviewRoute;
  "/stores/create": typeof AuthorizedLayoutStoresCreateRoute;
  "/stores": typeof AuthorizedLayoutStoresIndexRoute;
  "/orders/$id": typeof AuthorizedLayoutDashboardLayoutOrdersIdRoute;
  "/orders/create": typeof AuthorizedLayoutDashboardLayoutOrdersCreateRoute;
  "/products/$id": typeof AuthorizedLayoutDashboardLayoutProductsIdRoute;
  "/settings/general": typeof AuthorizedLayoutDashboardLayoutSettingsGeneralRoute;
  "/orders": typeof AuthorizedLayoutDashboardLayoutOrdersIndexRoute;
  "/products": typeof AuthorizedLayoutDashboardLayoutProductsIndexRoute;
  "/settings": typeof AuthorizedLayoutDashboardLayoutSettingsIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthorizedLayoutDashboardLayoutRouteWithChildren;
  "/auth-verification": typeof AuthLayoutAuthVerificationRoute;
  "/sign-in": typeof AuthLayoutSignInRoute;
  "/sign-up": typeof AuthLayoutSignUpRoute;
  "/account": typeof AuthorizedLayoutAccountRoute;
  "/categories": typeof AuthorizedLayoutDashboardLayoutCategoriesRoute;
  "/collections": typeof AuthorizedLayoutDashboardLayoutCollectionsRoute;
  "/customers": typeof AuthorizedLayoutDashboardLayoutCustomersRoute;
  "/files": typeof AuthorizedLayoutDashboardLayoutFilesRoute;
  "/inventory": typeof AuthorizedLayoutDashboardLayoutInventoryRoute;
  "/overview": typeof AuthorizedLayoutDashboardLayoutOverviewRoute;
  "/stores/create": typeof AuthorizedLayoutStoresCreateRoute;
  "/stores": typeof AuthorizedLayoutStoresIndexRoute;
  "/orders/$id": typeof AuthorizedLayoutDashboardLayoutOrdersIdRoute;
  "/orders/create": typeof AuthorizedLayoutDashboardLayoutOrdersCreateRoute;
  "/products/$id": typeof AuthorizedLayoutDashboardLayoutProductsIdRoute;
  "/settings/general": typeof AuthorizedLayoutDashboardLayoutSettingsGeneralRoute;
  "/orders": typeof AuthorizedLayoutDashboardLayoutOrdersIndexRoute;
  "/products": typeof AuthorizedLayoutDashboardLayoutProductsIndexRoute;
  "/settings": typeof AuthorizedLayoutDashboardLayoutSettingsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_auth-layout": typeof AuthLayoutRouteWithChildren;
  "/_authorized-layout": typeof AuthorizedLayoutRouteWithChildren;
  "/_auth-layout/auth-verification": typeof AuthLayoutAuthVerificationRoute;
  "/_auth-layout/sign-in": typeof AuthLayoutSignInRoute;
  "/_auth-layout/sign-up": typeof AuthLayoutSignUpRoute;
  "/_authorized-layout/_dashboard-layout": typeof AuthorizedLayoutDashboardLayoutRouteWithChildren;
  "/_authorized-layout/account": typeof AuthorizedLayoutAccountRoute;
  "/_authorized-layout/_dashboard-layout/categories": typeof AuthorizedLayoutDashboardLayoutCategoriesRoute;
  "/_authorized-layout/_dashboard-layout/collections": typeof AuthorizedLayoutDashboardLayoutCollectionsRoute;
  "/_authorized-layout/_dashboard-layout/customers": typeof AuthorizedLayoutDashboardLayoutCustomersRoute;
  "/_authorized-layout/_dashboard-layout/files": typeof AuthorizedLayoutDashboardLayoutFilesRoute;
  "/_authorized-layout/_dashboard-layout/inventory": typeof AuthorizedLayoutDashboardLayoutInventoryRoute;
  "/_authorized-layout/_dashboard-layout/overview": typeof AuthorizedLayoutDashboardLayoutOverviewRoute;
  "/_authorized-layout/stores/create": typeof AuthorizedLayoutStoresCreateRoute;
  "/_authorized-layout/stores/": typeof AuthorizedLayoutStoresIndexRoute;
  "/_authorized-layout/_dashboard-layout/orders/$id": typeof AuthorizedLayoutDashboardLayoutOrdersIdRoute;
  "/_authorized-layout/_dashboard-layout/orders/create": typeof AuthorizedLayoutDashboardLayoutOrdersCreateRoute;
  "/_authorized-layout/_dashboard-layout/products/$id": typeof AuthorizedLayoutDashboardLayoutProductsIdRoute;
  "/_authorized-layout/_dashboard-layout/settings/general": typeof AuthorizedLayoutDashboardLayoutSettingsGeneralRoute;
  "/_authorized-layout/_dashboard-layout/orders/": typeof AuthorizedLayoutDashboardLayoutOrdersIndexRoute;
  "/_authorized-layout/_dashboard-layout/products/": typeof AuthorizedLayoutDashboardLayoutProductsIndexRoute;
  "/_authorized-layout/_dashboard-layout/settings/": typeof AuthorizedLayoutDashboardLayoutSettingsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/auth-verification"
    | "/sign-in"
    | "/sign-up"
    | "/account"
    | "/categories"
    | "/collections"
    | "/customers"
    | "/files"
    | "/inventory"
    | "/overview"
    | "/stores/create"
    | "/stores"
    | "/orders/$id"
    | "/orders/create"
    | "/products/$id"
    | "/settings/general"
    | "/orders"
    | "/products"
    | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/auth-verification"
    | "/sign-in"
    | "/sign-up"
    | "/account"
    | "/categories"
    | "/collections"
    | "/customers"
    | "/files"
    | "/inventory"
    | "/overview"
    | "/stores/create"
    | "/stores"
    | "/orders/$id"
    | "/orders/create"
    | "/products/$id"
    | "/settings/general"
    | "/orders"
    | "/products"
    | "/settings";
  id:
    | "__root__"
    | "/"
    | "/_auth-layout"
    | "/_authorized-layout"
    | "/_auth-layout/auth-verification"
    | "/_auth-layout/sign-in"
    | "/_auth-layout/sign-up"
    | "/_authorized-layout/_dashboard-layout"
    | "/_authorized-layout/account"
    | "/_authorized-layout/_dashboard-layout/categories"
    | "/_authorized-layout/_dashboard-layout/collections"
    | "/_authorized-layout/_dashboard-layout/customers"
    | "/_authorized-layout/_dashboard-layout/files"
    | "/_authorized-layout/_dashboard-layout/inventory"
    | "/_authorized-layout/_dashboard-layout/overview"
    | "/_authorized-layout/stores/create"
    | "/_authorized-layout/stores/"
    | "/_authorized-layout/_dashboard-layout/orders/$id"
    | "/_authorized-layout/_dashboard-layout/orders/create"
    | "/_authorized-layout/_dashboard-layout/products/$id"
    | "/_authorized-layout/_dashboard-layout/settings/general"
    | "/_authorized-layout/_dashboard-layout/orders/"
    | "/_authorized-layout/_dashboard-layout/products/"
    | "/_authorized-layout/_dashboard-layout/settings/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
  AuthorizedLayoutRoute: typeof AuthorizedLayoutRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthorizedLayoutRoute: AuthorizedLayoutRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth-layout",
        "/_authorized-layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth-layout": {
      "filePath": "_auth-layout.tsx",
      "children": [
        "/_auth-layout/auth-verification",
        "/_auth-layout/sign-in",
        "/_auth-layout/sign-up"
      ]
    },
    "/_authorized-layout": {
      "filePath": "_authorized-layout.tsx",
      "children": [
        "/_authorized-layout/_dashboard-layout",
        "/_authorized-layout/account",
        "/_authorized-layout/stores/create",
        "/_authorized-layout/stores/"
      ]
    },
    "/_auth-layout/auth-verification": {
      "filePath": "_auth-layout/auth-verification.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/sign-in": {
      "filePath": "_auth-layout/sign-in.tsx",
      "parent": "/_auth-layout"
    },
    "/_auth-layout/sign-up": {
      "filePath": "_auth-layout/sign-up.tsx",
      "parent": "/_auth-layout"
    },
    "/_authorized-layout/_dashboard-layout": {
      "filePath": "_authorized-layout/_dashboard-layout.tsx",
      "parent": "/_authorized-layout",
      "children": [
        "/_authorized-layout/_dashboard-layout/categories",
        "/_authorized-layout/_dashboard-layout/collections",
        "/_authorized-layout/_dashboard-layout/customers",
        "/_authorized-layout/_dashboard-layout/files",
        "/_authorized-layout/_dashboard-layout/inventory",
        "/_authorized-layout/_dashboard-layout/overview",
        "/_authorized-layout/_dashboard-layout/orders/$id",
        "/_authorized-layout/_dashboard-layout/orders/create",
        "/_authorized-layout/_dashboard-layout/products/$id",
        "/_authorized-layout/_dashboard-layout/settings/general",
        "/_authorized-layout/_dashboard-layout/orders/",
        "/_authorized-layout/_dashboard-layout/products/",
        "/_authorized-layout/_dashboard-layout/settings/"
      ]
    },
    "/_authorized-layout/account": {
      "filePath": "_authorized-layout/account.tsx",
      "parent": "/_authorized-layout"
    },
    "/_authorized-layout/_dashboard-layout/categories": {
      "filePath": "_authorized-layout/_dashboard-layout/categories.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/collections": {
      "filePath": "_authorized-layout/_dashboard-layout/collections.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/customers": {
      "filePath": "_authorized-layout/_dashboard-layout/customers.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/files": {
      "filePath": "_authorized-layout/_dashboard-layout/files.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/inventory": {
      "filePath": "_authorized-layout/_dashboard-layout/inventory.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/overview": {
      "filePath": "_authorized-layout/_dashboard-layout/overview.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/stores/create": {
      "filePath": "_authorized-layout/stores/create.tsx",
      "parent": "/_authorized-layout"
    },
    "/_authorized-layout/stores/": {
      "filePath": "_authorized-layout/stores/index.tsx",
      "parent": "/_authorized-layout"
    },
    "/_authorized-layout/_dashboard-layout/orders/$id": {
      "filePath": "_authorized-layout/_dashboard-layout/orders/$id.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/orders/create": {
      "filePath": "_authorized-layout/_dashboard-layout/orders/create.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/products/$id": {
      "filePath": "_authorized-layout/_dashboard-layout/products/$id.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/settings/general": {
      "filePath": "_authorized-layout/_dashboard-layout/settings/general.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/orders/": {
      "filePath": "_authorized-layout/_dashboard-layout/orders/index.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/products/": {
      "filePath": "_authorized-layout/_dashboard-layout/products/index.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    },
    "/_authorized-layout/_dashboard-layout/settings/": {
      "filePath": "_authorized-layout/_dashboard-layout/settings/index.tsx",
      "parent": "/_authorized-layout/_dashboard-layout"
    }
  }
}
ROUTE_MANIFEST_END */
